CSC59939/studY

- frontend/src/actions/authActions.js
- frontend/src/components/eventForm/eventForm.js
- frontend/src/components/eventForm/eventForm.test.js
- frontend/src/components/header/header.test.js
- frontend/src/components/login/login.js
- frontend/src/components/register/register.js
jest tests for create event form and redirect on successful login / register to homepage.
> Event form tests and redirecting

- frontend/package-lock.json
- frontend/src/components/EventHomePage/EventHomePage.js
- frontend/src/components/EventHomePage/EventHomePage.styles.js
- frontend/src/components/EventHomePage/EventHomePage.test.js
- frontend/src/components/EventHomePage/__snapshots__/EventHomePage.test.js.snap
- frontend/src/components/EventList/EventList.js
- frontend/src/components/EventList/EventList.styles.js
- frontend/src/components/EventList/EventList.test.js
- frontend/src/components/EventList/EventListCard.js
- frontend/src/containers/EventPage/EventPage.js
Could someone take look, my test are failing whenever I do a full render (mount or snapshot) if a component uses link without <Router>
> some test for events

- backend/events/tests.py
Hey moustafa i couldnt make the test for Event, the fk always gets me error.
> Model test

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/EventList/EventList.js
- frontend/src/components/EventList/EventList.styles.js
- frontend/src/components/EventList/EventListCard.js
Some initial styling for event list page. Let me know what you think.
> Event List styles

- frontend/src/containers/EventPage/EventPage.js
if a user enters a route to an event that does not exist, error message will pop up instead of an error
> Event does not exist exception

- frontend/src/components/EventList/EventList.js
- frontend/src/components/SubtopicPage/SubtopicPage.js
- frontend/src/containers/EventListPage/EventListPage.js
- frontend/src/fetches.js
> connecting pages

- backend/events/api.py
- backend/events/serializers.py
- backend/events/urls.py
* event routes
event list: `GET /api/events` => filters {userId, campus, topic, category}
event detail: `GET /api/events/{id}`
create event: `POST /api/events`
delete event: `DELETE /api/events/{id}`
* nested route for event guests
event attendees: `GET /api/events/{id}/attendees`
join event: `POST /api/events/{id}/attendees`
leave event: `DELETE /api/events/{id}/attendees`
> updated routes

- frontend/package-lock.json
- frontend/src/App.js
- frontend/src/components/EventList/EventListCard.js
- frontend/src/components/SubtopicPage/SubtopicPage.js
- frontend/src/components/UserProfilePage/UserProfilePage.js
- frontend/src/components/UserProfilePage/UserProfilePage.styles.js
- frontend/src/components/header/header.js
- frontend/src/components/index.js
- frontend/src/containers/UserProfile/UserProfile.js
- frontend/src/containers/index.js
- frontend/src/index.js
user profile page with user name, email, school, major info created. './profile' route was conflicting with './:category' route, so I couldn't come up with any better solution as to change '/:category' to '/category/:category' and same with the corresponding routes.
> UserProfilePage

- frontend/src/components/EventList/EventList.js
- frontend/src/components/header/header.js
- frontend/src/components/header/header.test.js
- frontend/src/containers/EventListPage/EventListPage.js
- frontend/src/containers/EventPage/EventPage.js
- frontend/src/contexts/Auth.context.js
- frontend/src/index.js
closes #112 #115 
Bunch of small bug fixes and polish to `event-list` and `event-homepage`
- Dynamically load event attendees when joining/leaving event
- event calendar now shows correct event date
- disabled `create event` button if user not logged in
- fixed bad token error (redirects to homepage if bad token)
- fixed delete event button persisting after owner log out.
> Bug fixes and polish

- frontend/src/containers/EventPage/EventPage.js
- frontend/src/contexts/Auth.context.js
close #121 
Fixed redirecting page on reload.
> fixed redirecting on reload

- backend/events/tests/factories.py
- backend/events/tests/tests_api.py
- frontend/.eslintrc.json
unit tests for event api actions
closes #148
> event actions unit tests

- backend/accounts/api.py
- backend/accounts/serializers.py
- backend/accounts/signals.py
- backend/accounts/tests.py
- backend/events/api.py
- backend/events/tests/factories.py
- backend/events/tests/tests_api.py
+ update signup endpoint to return auth token in the response
> improve tests

- frontend/src/components/SubtopicPage/SubtopicPage.js
- frontend/src/components/SubtopicPage/SubtopicPage.test.js
small test for SubtopicPage component
> SubtopicPage test

- README.md
- frontend/src/components/login/login.js
- frontend/src/components/register/register.js
The readme is updated with the right roles. Removed the links from the modal.
> removed sign up and sign in button, and updated readme roles

- frontend/src/components/eventForm/eventForm.js
- frontend/src/components/login/login.js
- frontend/src/components/register/register.js
close #150 
fixed form lag. 
- register
- login
- eventForm
> form lag fix

- backend/post_release.sh
Changed the script to repopulate the lat and long.
> added deployed db fix, and added superuser

- .travis.yml
- frontend/package.json
small fix to linting script
`npm run lint` from root dir should lint the `src` folder
> fixed linting script

- backend/accounts/api.py
- backend/accounts/urls.py
- backend/events/api.py
- backend/events/management/commands/topicsdb.py
- backend/events/urls.py
- close #122 
the UpdateModelMixin from drf didnt allow me to overwrite the user model, so i had to do my own put function. Idk how else I could have done it. 
https://i.imgur.com/F7bbcKU.png
> Profile-edit

- backend/events/admin.py
- backend/events/api.py
- backend/events/models.py
- backend/events/serializers.py
- backend/events/urls.py
- close #158 
This new feature will allow users to comment on the event page. 
fetching by event will is as follow: api/comment?event=#, where # is the event_id
creating is similar to create event, but in this case we only have two fields: message & upvote
- upvote will serve as a best comment and will be always be on top, sorted 
missing update/edit
> added new model comment, with api to fetch and create

- backend/accounts/serializers.py
- backend/events/api.py
- backend/events/urls.py
- change request method to *PATCH* to allow partial updates
- implement permission check for update profile view
- add organizer field to event query filters
> profile update permissions & remove redundant code

- frontend/package-lock.json
- frontend/src/components/EventHomePage/EventHomePage.js
- frontend/src/components/EventList/EventListCard.js
- frontend/src/components/UserProfilePage/UserProfilePage.js
- frontend/src/components/UserProfilePage/UserProfilePage.test.js
- frontend/src/components/comments/comments.js
- frontend/src/components/login/__snapshots__/login.test.js.snap
- frontend/src/components/login/login.test.js
- frontend/src/components/register/__snapshots__/register.test.js.snap
- frontend/src/components/register/register.test.js
- frontend/src/containers/EventPage/EventPage.js
- frontend/src/containers/EventUserPropfile/EventUserProfile.js
- frontend/src/containers/UserProfile/UserProfile.js
- frontend/src/containers/index.js
- frontend/src/fetches.js
- frontend/src/index.js
In the gif it looks like there is some delay but there isn't
> View event attendee profile
